dist: trusty
sudo: required
language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
  - nix
before_install:
- sudo mkdir -m 0755 /nix && sudo chown travis /nix
- curl https://nixos.org/nix/install | sh 
- . /home/travis/.nix-profile/etc/profile.d/nix.sh
- nix-channel --add https://nix.dapphub.com/pkgs/dapphub
- nix-channel --update
- nix-env -iA dapphub.{dapp,seth,hevm,solc}
- npm i -g npm@latest
install:
- sed -i '13s/DSToken.*/WETH9)/' ./lib/sai/bin/deploy
- npm install
- npm run build:backend
- npm run build:frontend
before_script:
- npm install -g codecov
script:
- chmod +x with-deployed-system update-abis
- npm run test
- codecov
after_install:
- cat /home/travis/.npm/_logs/2018-02-*.log
deploy:
  provider: npm
  skip_cleanup: true
  email: joseph.luccisano@gmail.com
  on:
    tags: true
  api_key:
    secure: L/41Xcy55Sa9ee5aEj/63HZELFua+qC7swY56xYcYTTimo71dLhNzvh2DD0pGLAALAb2euC/7i/3zt7DJfGFPMZMipc2efZwDUhl/X4IlCXJyqlEf/gogGa+OoKBnA/9UyDeAAToqU5taBvQwhIedGB9uHpwHwrzRasilpjlbEk4hZZQskwBRJODHEmojZpQVWzeosSozY7sVPZN8mbG+BMu7+bUE4HeUVX8UQ+jbO59WGWDQ5QO+cAC6npA4ipCAFm/udQlXikCxNmGMGf1zzbqe3Be04loZwYPvJG2VlhjRaLUA8QEi865+aEPbZFhpdyFS93CfHQJvJAOvDEA2gjkXCyc9HgLa/Gvq+p6InqVG2iBvegFlmRrx7IN/aJYRwtwma/q06V5ueA73jPkOhyd9kshOIPOL5sXmLk9F6UleETt60zTzUqtm4SShm7YRR4Z9yxQvIwBteCDJzy6OAgVAUAdb92srLardyKARVmLqKzaPw5KR3NIDz4iRSU9IlVCKKJ9O4zQQSf3qvARc0XmGOzdT9E86MsbdEzO9a9bAmxCGtmXDCBDbgjY5XkMpCxhN3a7iflEn4vLhNuGLqFyF6XHD2nTnKAktT7AHi+O4K3l4XbaQCM0iKD0yW5U/9VIzLjhlzHbu0byTmZJfHrB7xKklQWUBVl327hZvb0=
