dist: trusty
sudo: required
language: node_js
node_js:
- '8'
before_cache:
- nix-collect-garbage -d
cache:
  directories:
  - node_modules
  - nix
  timeout: 9000
before_install:
- sudo mkdir -m 0755 /nix && sudo chown travis /nix
- sudo mount -o bind /home/travis/build/makerdao/makerdao-integration-poc/nix /nix
- source ./scripts/install-dapptools.sh
- npm i -g npm@latest
install:
- npm install
- npm run build:backend
- npm run build:frontend
before_script:
- npm install -g codecov
script:
- npm run coverage
- codecov
after_install:
- cat /home/travis/.npm/_logs/2018-02-*.log
