dist: trusty
language: node_js
node_js:
- '7'
cache:
  directories:
  - node_modules
before_install:
- git clone https://github.com/dapphub/dapp; cd dapp; make link prefix=/tmp/dep/; cd ..
- wget https://github.com/rainbreak/solidity-static/releases/download/v0.4.10/solc
- install solc /tmp/dep/bin/
- wget https://github.com/dapphub/ethrun/releases/download/v0.2.4/ethrun-v0.2.4-linux
- install ethrun-v0.2.4-linux /tmp/dep/bin/ethrun
- export PATH=$PATH:/tmp/dep/bin/
- npm i -g npm@^5.3.0
install:
- echo "dapp tools already installed"
- npm install
- npm run build
before_script:
- npm install -g codecov
script:
- dapp test
- npm run test
- codecov
deploy:
  provider: npm
  skip_cleanup: true
  email: joseph.luccisano@gmail.com
  on:
    tags: true
  api_key:
    secure: L/41Xcy55Sa9ee5aEj/63HZELFua+qC7swY56xYcYTTimo71dLhNzvh2DD0pGLAALAb2euC/7i/3zt7DJfGFPMZMipc2efZwDUhl/X4IlCXJyqlEf/gogGa+OoKBnA/9UyDeAAToqU5taBvQwhIedGB9uHpwHwrzRasilpjlbEk4hZZQskwBRJODHEmojZpQVWzeosSozY7sVPZN8mbG+BMu7+bUE4HeUVX8UQ+jbO59WGWDQ5QO+cAC6npA4ipCAFm/udQlXikCxNmGMGf1zzbqe3Be04loZwYPvJG2VlhjRaLUA8QEi865+aEPbZFhpdyFS93CfHQJvJAOvDEA2gjkXCyc9HgLa/Gvq+p6InqVG2iBvegFlmRrx7IN/aJYRwtwma/q06V5ueA73jPkOhyd9kshOIPOL5sXmLk9F6UleETt60zTzUqtm4SShm7YRR4Z9yxQvIwBteCDJzy6OAgVAUAdb92srLardyKARVmLqKzaPw5KR3NIDz4iRSU9IlVCKKJ9O4zQQSf3qvARc0XmGOzdT9E86MsbdEzO9a9bAmxCGtmXDCBDbgjY5XkMpCxhN3a7iflEn4vLhNuGLqFyF6XHD2nTnKAktT7AHi+O4K3l4XbaQCM0iKD0yW5U/9VIzLjhlzHbu0byTmZJfHrB7xKklQWUBVl327hZvb0=
